services:
  postgres:
    image: postgres:16-alpine
    container_name: data_processing_db_ai-agent
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: data_processing
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data_processing:/var/lib/postgresql/data
    restart: always

#  ai-agent:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: data_processing_ai-agent
#    container_name: data_processing_ai-agent
#    ports:
#      - "8000:8000"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    restart: always

volumes:
  pg_data_processing: